<a href="https://colab.research.google.com/github/envirodatascience/final-project-insect-team/blob/main/Precipitation_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1: Import modules, read in data

In [7]:
# load the pandas package and read in the data frame
import pandas as pd
url = 'https://www.ncei.noaa.gov/orders/cdo/3997103.csv'
df = pd.read_csv(url)

1.1 Look into the data

In [ ]:
   #first rows of the data
df.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,PRCP_ATTRIBUTES
0,USC00067002,"ROUND POND, CT US",41.3008,-73.5369,243.8,1949,38.41,",0"
1,USC00067002,"ROUND POND, CT US",41.3008,-73.5369,243.8,1950,47.65,",0"
2,USC00067002,"ROUND POND, CT US",41.3008,-73.5369,243.8,1951,54.05,",0"
3,USC00067002,"ROUND POND, CT US",41.3008,-73.5369,243.8,1952,60.71,",0"
4,USC00067002,"ROUND POND, CT US",41.3008,-73.5369,243.8,1953,49.63,",0"

In [8]:
#the types of columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3910 entries, 0 to 3909
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATION    3910 non-null   object
 1   NAME       3910 non-null   object
 2   LATITUDE   3910 non-null   float64
 3   LONGITUDE  3910 non-null   float64
 4   ELEVATION  3910 non-null   float64
 5   DATE       3910 non-null   int64
 6   PRCP       3364 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 214.0+ KB

In [9]:
#the shape of the data
df.shape

(3910, 7)

In [ ]:
#column names
df.columns

Index(['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'PRCP',
       'PRCP_ATTRIBUTES'],
      dtype='object')

# Describing the Data

In [10]:
df.describe()

          LATITUDE    LONGITUDE    ELEVATION         DATE         PRCP
count  3910.000000  3910.000000  3910.000000  3910.000000  3364.000000
mean     41.586961   -72.837674   116.722532  1972.158568    48.063199
std       0.264447     0.494189    96.809515    33.756201     8.827999
min      41.062171   -73.700000     0.900000  1858.000000    18.350000
25%      41.350240   -73.229600    46.000000  1952.000000    42.010000
50%      41.583300   -72.933330    91.400000  1969.000000    47.275000
75%      41.795100   -72.392810   167.600000  1999.000000    53.712500
max      42.027433   -71.830421   438.900000  2025.000000    88.520000

# Handle missing data

In [11]:
#find missing data
df.isnull().sum()

STATION        0
NAME           0
LATITUDE       0
LONGITUDE      0
ELEVATION      0
DATE           0
PRCP         546
dtype: int64

In [12]:
#find rows with the NAs
df[df.isna().any(axis=1)]

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP
41,USC00067002,"ROUND POND, CT US",41.30080,-73.53690,243.8,1999,NaN
74,USC00069783,"WOODBURY 3 W, CT US",41.56667,-73.26667,285.0,1965,NaN
76,USC00067361,"DERBY SHELTON, CT US",41.31667,-73.08333,18.0,1887,NaN
77,USC00067361,"DERBY SHELTON, CT US",41.31667,-73.08333,18.0,1888,NaN
78,USC00067361,"DERBY SHELTON, CT US",41.31667,-73.08333,18.0,1889,NaN
...,...,...,...,...,...,...,...
3841,USC00064767,"MIDDLETOWN 4 W, CT US",41.55000,-72.71667,112.5,1992,NaN
3846,USC00064767,"MIDDLETOWN 4 W, CT US",41.55000,-72.71667,112.5,1997,NaN
3848,USC00060961,"BULLS BRIDGE DAM, CT US",41.67630,-73.50860,79.2,1952,NaN
3867,USC00060961,"BULLS BRIDGE DAM, CT US",41.67630,-73.50860,79.2,1971,NaN
3889,USC00060961,"BULLS BRIDGE DAM, CT US",41.67630,-73.50860,79.2,1994,NaN

In [13]:
#group by year of the NAs
df[df.isna().any(axis=1)].groupby('DATE').count()

      STATION  NAME  LATITUDE  LONGITUDE  ELEVATION  PRCP
DATE
1884        1     1         1          1          1     0
1885        2     2         2          2          2     0
1886        2     2         2          2          2     0
1887        2     2         2          2          2     0
1888        2     2         2          2          2     0
...       ...   ...       ...        ...        ...   ...
2021        3     3         3          3          3     0
2022        3     3         3          3          3     0
2023        2     2         2          2          2     0
2024        4     4         4          4          4     0
2025        9     9         9          9          9     0

[135 rows x 6 columns]

In [14]:
#drop NAs
df.dropna(inplace=True)

In [ ]:
#Rename some columns
#rename DATE to YEAR, STATION to STATION_ID,NAME TO STATION_NAME
df.rename(columns={'STATION': 'STATION_ID', 'NAME': 'STATION_NAME'}, inplace=True)

# Calculating Average precipitation per year

In [19]:
#average precipitation per year
df.groupby('DATE')['PRCP'].mean()

DATE
1858    41.890000
1859    53.310000
1860    37.380000
1861    47.030000
1862    48.020000
          ...
2020    45.709118
2021    53.334416
2022    46.398205
2023    62.344521
2024    54.480676
Name: PRCP, Length: 166, dtype: float64