<a href="https://colab.research.google.com/github/envirodatascience/final-project-insect-team/blob/main/temp_data_insect_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FINAL PROJECT: Insect Group

In this Colab, we will be summarizing temperature data by State and Year (2000-2024)

Data from NOAA: https://www.ncei.noaa.gov/cdo-web/datasets

Documentation: https://www.ncei.noaa.gov/data/global-summary-of-the-year/doc/GSOY_documentation.pdf

In [2]:
# import modules

import pandas as pd
import numpy as np

In [ ]:
# download the data
# TODO: save to GitHub, read in from there
df_temp = pd.read_csv('https://www.ncei.noaa.gov/orders/cdo/3998324.csv')

In [3]:
# load in 1900-2024 data
# github link https://github.com/envirodatascience/final-project-insect-team/blob/main/temp_data_1900-2024.csv
df_temp = pd.read_csv('temp_data_1900-2024.csv')

In [4]:
df_temp.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,DX70,DX90,EMNT,EMXT,HTDD,TAVG,TMAX,TMIN
0,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1966,NaN,NaN,-12.0,NaN,NaN,NaN,NaN,34.7
1,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1967,NaN,NaN,-21.0,NaN,NaN,NaN,NaN,33.4
2,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1968,144.0,14.0,-14.0,97.0,NaN,46.2,59.3,33.2
3,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1969,136.0,9.0,-6.0,95.0,7001.0,47.5,59.1,35.8
4,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1970,136.0,14.0,-18.0,95.0,7134.0,47.1,58.6,35.6

In [5]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2334 entries, 0 to 2333
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATION    2334 non-null   object
 1   NAME       2334 non-null   object
 2   LATITUDE   2334 non-null   float64
 3   LONGITUDE  2334 non-null   float64
 4   ELEVATION  2334 non-null   float64
 5   DATE       2334 non-null   int64
 6   DX70       1663 non-null   float64
 7   DX90       1663 non-null   float64
 8   EMNT       1678 non-null   float64
 9   EMXT       1663 non-null   float64
 10  HTDD       1576 non-null   float64
 11  TAVG       1610 non-null   float64
 12  TMAX       1663 non-null   float64
 13  TMIN       1678 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 255.4+ KB

Data Documentation:


*   STATION:
*   DATE: Year
*   DX70: Number days with maximum temperature greater than 70F (21.1C)
*   DX90: Number days with maximum temperature greater than 90F (32.2C)
*   EMNT: Extreme minimum temperature
*   EMXT: Extreme maximum temperature
*   HTDD: Heating Degree Days
*   TAVG: Average Average Temperature
*   TMAX: Average Maximum Temperature
*   TMIN: Average Minimum Temperature

In [6]:
# check for duplicate rows

df_temp.duplicated().sum()

np.int64(0)

In [7]:
# find nunique for years

df_temp['DATE'].unique()
# TODO: add a value counts line

array([1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948,
       1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959,
       1960, 1961, 1962, 1963, 1964, 1965, 1933, 1936, 1938, 1939, 1900,
       1901, 1902, 1903, 1904, 1935, 1937, 2009, 2010, 1905, 1906, 1907,
       1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918,
       1919, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931,
       1932, 1934, 1920, 1921])

In [8]:
# group data by year and temperature averages

df_temp.groupby(['STATION', 'DATE']).agg({'DX90': 'sum', 'EMNT': 'min', 'EMXT': 'max', 'TAVG': 'mean', 'TMAX': 'mean', 'TMIN': 'mean'}).reset_index()

          STATION  DATE  DX90  EMNT  EMXT  TAVG  TMAX  TMIN
0     USC00060227  1949   0.0   NaN   NaN   NaN   NaN   NaN
1     USC00060227  1950   0.0   NaN   NaN   NaN   NaN   NaN
2     USC00060227  1951   0.0   NaN   NaN   NaN   NaN   NaN
3     USC00060227  1952   0.0   NaN   NaN   NaN   NaN   NaN
4     USC00060227  1953   0.0   NaN   NaN   NaN   NaN   NaN
...           ...   ...   ...   ...   ...   ...   ...   ...
2329  USW00094702  2020  11.0  11.0  95.0  55.3  62.9  47.7
2330  USW00094702  2021  13.0  12.0  96.0  54.8  62.4  47.1
2331  USW00094702  2022  11.0   6.0  94.0  53.7  61.7  45.7
2332  USW00094702  2023   4.0  -4.0  93.0  54.8  62.5  47.1
2333  USW00094702  2024   7.0   9.0  93.0  55.2  62.8  47.6

[2334 rows x 8 columns]

In [9]:
# show rows with all missing values

df_temp[df_temp.isna().all(axis=1)]

Empty DataFrame
Columns: [STATION, NAME, LATITUDE, LONGITUDE, ELEVATION, DATE, DX70, DX90, EMNT, EMXT, HTDD, TAVG, TMAX, TMIN]
Index: []

In [10]:
# display rows with tavg, tmin, and tmax for the year data missing

df_temp[(df_temp['TAVG'].isna()) & (df_temp['TMIN'].isna()) & (df_temp['TMAX'].isna())]

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,DX70,DX90,EMNT,EMXT,HTDD,TAVG,TMAX,TMIN
13,USC00069388,"WEST THOMPSON LAKE, CT US",41.94420,-71.90310,109.7,1979,NaN,NaN,NaN,NaN,6842.0,NaN,NaN,NaN
15,USC00069388,"WEST THOMPSON LAKE, CT US",41.94420,-71.90310,109.7,1981,NaN,NaN,NaN,NaN,7110.0,NaN,NaN,NaN
17,USC00069388,"WEST THOMPSON LAKE, CT US",41.94420,-71.90310,109.7,1983,NaN,NaN,NaN,NaN,6141.0,NaN,NaN,NaN
22,USC00069388,"WEST THOMPSON LAKE, CT US",41.94420,-71.90310,109.7,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,USC00069388,"WEST THOMPSON LAKE, CT US",41.94420,-71.90310,109.7,1990,NaN,NaN,NaN,NaN,6703.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2298,USC00060801,"BRIDGEPORT, CT US",41.20000,-73.20000,43.0,1948,NaN,NaN,NaN,NaN,6144.0,NaN,NaN,NaN
2301,USC00060801,"BRIDGEPORT, CT US",41.20000,-73.20000,43.0,1951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2302,USC00067958,"STAFFORDVILLE, CT US",41.99840,-72.26060,224.3,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2327,USC00060808,"TRUMBULL, CT US",41.22764,-73.17445,30.5,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2333,USC00060808,"TRUMBULL, CT US",41.22764,-73.17445,30.5,2018,NaN,NaN,NaN,NaN,5474.0,NaN,NaN,NaN

In [11]:
# drop these rows of data
# TODO: add justification for dropping NAs, other decisions
df_temp_clean = df_temp.drop(df_temp[(df_temp['TAVG'].isna()) & (df_temp['TMIN'].isna()) & (df_temp['TMAX'].isna())].index).reset_index(drop=True)

In [12]:
# check dataframe

df_temp_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATION    1731 non-null   object
 1   NAME       1731 non-null   object
 2   LATITUDE   1731 non-null   float64
 3   LONGITUDE  1731 non-null   float64
 4   ELEVATION  1731 non-null   float64
 5   DATE       1731 non-null   int64
 6   DX70       1663 non-null   float64
 7   DX90       1663 non-null   float64
 8   EMNT       1678 non-null   float64
 9   EMXT       1663 non-null   float64
 10  HTDD       1471 non-null   float64
 11  TAVG       1610 non-null   float64
 12  TMAX       1663 non-null   float64
 13  TMIN       1678 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 189.5+ KB

In [13]:
df_temp_clean.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,DX70,DX90,EMNT,EMXT,HTDD,TAVG,TMAX,TMIN
0,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1966,NaN,NaN,-12.0,NaN,NaN,NaN,NaN,34.7
1,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1967,NaN,NaN,-21.0,NaN,NaN,NaN,NaN,33.4
2,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1968,144.0,14.0,-14.0,97.0,NaN,46.2,59.3,33.2
3,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1969,136.0,9.0,-6.0,95.0,7001.0,47.5,59.1,35.8
4,USC00069388,"WEST THOMPSON LAKE, CT US",41.9442,-71.9031,109.7,1970,136.0,14.0,-18.0,95.0,7134.0,47.1,58.6,35.6

In [15]:
# get a summary of the average, average maximum, and average minimum temperatures by year for each location

df_yearly = df_temp_clean.groupby(['DATE']).agg({'TMIN': 'mean', 'TAVG': 'mean', 'TMAX': 'mean'}).reset_index()
df_yearly.head()

   DATE       TMIN       TAVG       TMAX
0  1900  40.883333  51.050000  60.814286
1  1901  39.242857  49.040000  58.583333
2  1902  39.600000  49.420000  59.540000
3  1903  38.928571  48.785714  58.657143
4  1904  35.600000  46.025000  56.228571

In [18]:
df_yearly.to_csv('noaa_temp_yearly_ct.csv', index=False)